name: release
description: release assets on tag

inputs:
  binary:
    description: path to a binary (automatically added .exe for windows)
    required: true

runs:
  using: composite
  steps:
    - id: config
      run: |
        test "$GOOS"
        test "$GOARCH"
        echo "::set-output name=zip::${{ inputs.binary }}_${GOOS}_${GOARCH}.zip"
        echo "::set-output name=sha::${{ inputs.binary }}_${GOOS}_${GOARCH}.zip.sha256"
        if [[ $GOOS == windows ]]; then
          echo "::set-output name=binary::${{ inputs.binary }}.exe"
        else
          echo "::set-output name=binary::${{ inputs.binary }}"
        fi
      shell: bash

    # archive
    - run: test -f "${{ steps.config.outputs.binary }}"
    - if: runner.os != 'Windows'
      run: zip ${{ steps.config.outputs.zip }} ${{ steps.config.outputs.binary }} LICENSE README.md
      shell: bash
    - if: runner.os == 'Windows'
      run: powershell Compress-Archive -Path ${{ steps.config.outputs.binary }},LICENSE,README.md -DestinationPath ${{ steps.config.outputs.zip }}
      shell: bash

    # digest
    - if: runner.os != 'macOS'
      run: sha256sum -b ${{ steps.config.outputs.zip }} > ${{ steps.config.outputs.sha }}
      shell: bash
    - if: runner.os == 'macOS'
      run: shasum -a 256 -b ${{ steps.config.outputs.zip }} > ${{ steps.config.outputs.sha }}
      shell: bash
    - run: cat ${{ steps.config.outputs.sha }}
      shell: bash

    # upload
    - if: startsWith(github.ref, 'refs/tags/')
      run: gh release upload "${GITHUB_REF/refs\/tags\//}" ${{ steps.config.outputs.zip }} ${{ steps.config.outputs.sha }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
