name: release
description: release assets on tag

inputs:
  binary:
    description: path to a binary (automatically added .exe for windows)
    required: true

runs:
  using: composite
  steps:
    - id: config
      run: |
        test "$GOOS"
        test "$GOARCH"
        echo "zip=${{ inputs.binary }}_${GOOS}_${GOARCH}.zip" >> $GITHUB_OUTPUT
        echo "sha=${{ inputs.binary }}_${GOOS}_${GOARCH}.zip.sha256" >> $GITHUB_OUTPUT
        if [[ $GOOS == windows ]]; then
          echo "binary=${{ inputs.binary }}.exe" >> $GITHUB_OUTPUT
        else
          echo "binary=${{ inputs.binary }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    # archive
    - run: test -f "${{ steps.config.outputs.binary }}"
      shell: bash
    - if: runner.os != 'Windows'
      run: zip ${{ steps.config.outputs.zip }} ${{ steps.config.outputs.binary }} LICENSE README.md
      shell: bash
    - if: runner.os == 'Windows'
      run: powershell Compress-Archive -Path ${{ steps.config.outputs.binary }},LICENSE,README.md -DestinationPath ${{ steps.config.outputs.zip }}
      shell: bash

    # digest
    - if: runner.os != 'macOS'
      run: sha256sum -b ${{ steps.config.outputs.zip }} > ${{ steps.config.outputs.sha }}
      shell: bash
    - if: runner.os == 'macOS'
      run: shasum -a 256 -b ${{ steps.config.outputs.zip }} > ${{ steps.config.outputs.sha }}
      shell: bash
    - run: cat ${{ steps.config.outputs.sha }}
      shell: bash

    # upload
    - if: github.ref_type == 'tag'
      run: gh release upload '${{ github.ref_name }}' ${{ steps.config.outputs.zip }} ${{ steps.config.outputs.sha }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
