name: go-release-action/create-draft-release
description: Create a draft release
inputs:
  release-name:
    description: Release name to create
    required: true
  token:
    description: GitHub token to create a release
    required: false
    default: ${{ github.token }}
outputs:
  already-exists:
    description: Returns true if the release already exists
    value: ${{ steps.create.outputs.already-exists }}
runs:
  using: composite
  steps:
    - id: create
      name: Create a draft release if not exists
      shell: bash
      run: |
        if [[ -z "$release_name" ]]; then
          echo "No release-name is specified. Skip creating a release." >&2
          exit 0
        fi
        if gh release view --repo "$GITHUB_REPOSITORY" "$release_name"; then
          echo "Release $release_name already exists. Skip creating a release." >&2
          echo "already-exists=true" >> "$GITHUB_OUTPUT"
          exit 0
        fi
        gh release create --draft --repo "$GITHUB_REPOSITORY" --target "$GITHUB_SHA" --title "$release_name" "$release_name"
      env:
        release_name: ${{ inputs.release-name }}
        GITHUB_TOKEN: ${{ inputs.token }}
