name: test

on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - fixture/**
  push:
    branches:
      - v2
    tags:
      - test/release/*
    paths:
      - .github/workflows/test.yaml
      - fixture/**

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runs-on: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - runs-on: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - runs-on: windows-latest
            GOOS: windows
            GOARCH: amd64
    runs-on: ${{ matrix.platform.runs-on }}
    env:
      GOOS: ${{ matrix.platform.GOOS }}
      GOARCH: ${{ matrix.platform.GOARCH }}
    timeout-minutes: 10
    defaults:
      run:
        working-directory: fixture
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.6
      - run: go build
      - id: go-release-action
        uses: ./ # int128/go-release-action@v2
        with:
          working-directory: fixture
          binary: fixture
      - run: ls -l '${{ steps.go-release-action.outputs.zip-name }}'
      - run: zipinfo '${{ steps.go-release-action.outputs.zip-name }}'
