name: test

on:
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - fixture/**
  push:
    branches:
      - v2
    tags:
      - test/release/*
    paths:
      - .github/workflows/test.yaml
      - fixture/**

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runs-on: ubuntu-latest
            GOOS: linux
            GOARCH: amd64
          - runs-on: macos-latest
            GOOS: darwin
            GOARCH: amd64
          - runs-on: windows-latest
            GOOS: windows
            GOARCH: amd64
    runs-on: ${{ matrix.platform.runs-on }}
    env:
      GOOS: ${{ matrix.platform.GOOS }}
      GOARCH: ${{ matrix.platform.GOARCH }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: fixture/go.mod
      - run: go build
        working-directory: fixture
      - name: Run int128/go-release-action
        id: go-release-action
        uses: ./
        with:
          working-directory: fixture
          binary: fixture
      - run: ls -l '${{ steps.go-release-action.outputs.zip-name }}'
        working-directory: fixture
      - run: zipinfo '${{ steps.go-release-action.outputs.zip-name }}'
        working-directory: fixture
